"""RoadGuard AI: predictive maintenance and risk intelligence for road infrastructure."""

from __future__ import annotations

__version__ = "0.1.0"

from roadguard.config import ENV_PREFIX, ConfigError, RoadGuardConfig, load_config
from roadguard.contracts import (
    DatasetSpec,
    RiskBand,
    RiskBands,
    V1Contract,
)
from roadguard.data_quality import (
    CleaningResult,
    CorruptionEntry,
    CorruptionManifest,
    ValidationIssue,
    ValidationReport,
    clean_raw_dataset,
    inject_observation_corruption,
    validate_cleaned_dataset,
    validate_raw_dataset,
)
from roadguard.database import (
    DatabaseConfigurationError,
    DatabaseUnavailableError,
    LoadReport,
    PersistenceConflict,
    PersistenceError,
    PostgresRepository,
    RepositoryExport,
    RepositoryInputError,
    SegmentHistory,
    create_database_engine,
    initialize_database,
    load_cleaning_result,
)
from roadguard.eda import (
    CategoricalLevel,
    CategoricalSummary,
    ClassificationBalance,
    DataQualitySummary,
    DateSummary,
    EDAError,
    EDAReport,
    NumericSummary,
    SplitInventory,
    TargetCorrelation,
    build_eda_report,
    render_data_card,
)
from roadguard.events import (
    GenerationError,
    decay_condition,
    generate_accident_timeline,
    generate_maintenance_events,
    month_transition,
    monthly_hazard,
    observation_dates,
)
from roadguard.features import (
    CLASSIFICATION_FEATURE_COLUMNS,
    FEATURE_COLUMNS,
    FEATURE_FRAME_COLUMNS,
    FEATURE_KEY_COLUMNS,
    FEATURE_REGISTRY,
    REGRESSION_FEATURE_COLUMNS,
    FeatureDefinition,
    FeatureInputError,
    build_feature_frame,
)
from roadguard.observations import generate_observations
from roadguard.preprocessing import (
    ChronologicalSplit,
    PreprocessingError,
    PreprocessorFit,
    TransformedData,
    fit_preprocessor,
    split_chronologically,
    transform,
)
from roadguard.risk import risk_score_from_probability
from roadguard.segments import SegmentMaster, generate_segments
from roadguard.targets import (
    TARGET_COLUMNS,
    days_until_maintenance,
    derive_observation_targets,
    maintenance_within_30_days,
)

__all__ = [
    "CleaningResult",
    "ClassificationBalance",
    "CategoricalLevel",
    "CategoricalSummary",
    "ChronologicalSplit",
    "CLASSIFICATION_FEATURE_COLUMNS",
    "ConfigError",
    "CorruptionEntry",
    "CorruptionManifest",
    "DataQualitySummary",
    "DateSummary",
    "EDAError",
    "EDAReport",
    "ENV_PREFIX",
    "FEATURE_COLUMNS",
    "FEATURE_FRAME_COLUMNS",
    "FEATURE_KEY_COLUMNS",
    "FEATURE_REGISTRY",
    "DatasetSpec",
    "DatabaseConfigurationError",
    "DatabaseUnavailableError",
    "GenerationError",
    "FeatureDefinition",
    "FeatureInputError",
    "LoadReport",
    "NumericSummary",
    "PersistenceConflict",
    "PersistenceError",
    "PostgresRepository",
    "PreprocessingError",
    "PreprocessorFit",
    "RiskBand",
    "RiskBands",
    "REGRESSION_FEATURE_COLUMNS",
    "RoadGuardConfig",
    "RepositoryExport",
    "RepositoryInputError",
    "SegmentHistory",
    "SegmentMaster",
    "SplitInventory",
    "TARGET_COLUMNS",
    "TargetCorrelation",
    "TransformedData",
    "V1Contract",
    "ValidationIssue",
    "ValidationReport",
    "__version__",
    "clean_raw_dataset",
    "build_eda_report",
    "build_feature_frame",
    "create_database_engine",
    "days_until_maintenance",
    "decay_condition",
    "derive_observation_targets",
    "generate_accident_timeline",
    "generate_maintenance_events",
    "generate_observations",
    "generate_segments",
    "fit_preprocessor",
    "inject_observation_corruption",
    "initialize_database",
    "load_config",
    "load_cleaning_result",
    "maintenance_within_30_days",
    "month_transition",
    "monthly_hazard",
    "observation_dates",
    "risk_score_from_probability",
    "render_data_card",
    "split_chronologically",
    "transform",
    "validate_cleaned_dataset",
    "validate_raw_dataset",
]
