"""RoadGuard AI: predictive maintenance and risk intelligence for road infrastructure."""

from __future__ import annotations

__version__ = "0.1.0"

from roadguard.artifacts import (
    ARTIFACT_FILENAMES,
    FROZEN_SELECTION_CONTRACT_VERSION,
    RISK_BAND_NAMES,
    ArtifactFile,
    ArtifactPersistenceError,
    FrozenSelectionError,
    FrozenSelectionResult,
    RiskOutput,
    SelectedArtifactManifest,
    persist_selected_artifacts,
)
from roadguard.baselines import (
    BASELINE_CLASSIFIER_NAME,
    BASELINE_CONTRACT_VERSION,
    BASELINE_REGRESSOR_NAME,
    BaselineEvaluation,
    BaselineEvaluationError,
    ClassificationBaselineMetrics,
    RegressionBaselineMetrics,
    evaluate_baselines,
)
from roadguard.classification import (
    ADVANCED_CLASSIFIER_CONTRACT_VERSION,
    ADVANCED_CLASSIFIER_RNG_NAMESPACE,
    CANDIDATE_CLASSIFIER_NAMES,
    AdvancedClassificationError,
    AdvancedClassificationEvaluation,
    CandidateValidationMetrics,
    TestClassificationMetrics,
    evaluate_advanced_classifier,
)
from roadguard.config import ENV_PREFIX, ConfigError, RoadGuardConfig, load_config
from roadguard.contracts import (
    DatasetSpec,
    RiskBand,
    RiskBands,
    V1Contract,
)
from roadguard.data_quality import (
    CleaningResult,
    CorruptionEntry,
    CorruptionManifest,
    ValidationIssue,
    ValidationReport,
    clean_raw_dataset,
    inject_observation_corruption,
    validate_cleaned_dataset,
    validate_raw_dataset,
)
from roadguard.database import (
    DatabaseConfigurationError,
    DatabaseUnavailableError,
    LoadReport,
    PersistenceConflict,
    PersistenceError,
    PostgresRepository,
    RepositoryExport,
    RepositoryInputError,
    SegmentHistory,
    create_database_engine,
    initialize_database,
    load_cleaning_result,
)
from roadguard.eda import (
    CategoricalLevel,
    CategoricalSummary,
    ClassificationBalance,
    DataQualitySummary,
    DateSummary,
    EDAError,
    EDAReport,
    NumericSummary,
    SplitInventory,
    TargetCorrelation,
    build_eda_report,
    render_data_card,
)
from roadguard.events import (
    GenerationError,
    decay_condition,
    generate_accident_timeline,
    generate_maintenance_events,
    month_transition,
    monthly_hazard,
    observation_dates,
)
from roadguard.features import (
    CLASSIFICATION_FEATURE_COLUMNS,
    FEATURE_COLUMNS,
    FEATURE_FRAME_COLUMNS,
    FEATURE_KEY_COLUMNS,
    FEATURE_REGISTRY,
    REGRESSION_FEATURE_COLUMNS,
    FeatureDefinition,
    FeatureInputError,
    build_feature_frame,
)
from roadguard.observations import generate_observations
from roadguard.preprocessing import (
    ChronologicalSplit,
    PreprocessingError,
    PreprocessorFit,
    TransformedData,
    fit_preprocessor,
    split_chronologically,
    transform,
)
from roadguard.regression import (
    ADVANCED_REGRESSOR_CONTRACT_VERSION,
    ADVANCED_REGRESSOR_RNG_NAMESPACE,
    CANDIDATE_REGRESSOR_NAMES,
    AdvancedRegressionError,
    AdvancedRegressionEvaluation,
    CandidateRegressionValidationMetrics,
    TestRegressionMetrics,
    evaluate_advanced_regressor,
)
from roadguard.risk import risk_score_from_probability
from roadguard.segments import SegmentMaster, generate_segments
from roadguard.targets import (
    TARGET_COLUMNS,
    days_until_maintenance,
    derive_observation_targets,
    maintenance_within_30_days,
)

__all__ = [
    "ADVANCED_REGRESSOR_CONTRACT_VERSION",
    "ADVANCED_REGRESSOR_RNG_NAMESPACE",
    "ADVANCED_CLASSIFIER_CONTRACT_VERSION",
    "ADVANCED_CLASSIFIER_RNG_NAMESPACE",
    "AdvancedClassificationError",
    "AdvancedClassificationEvaluation",
    "AdvancedRegressionError",
    "AdvancedRegressionEvaluation",
    "ARTIFACT_FILENAMES",
    "ArtifactFile",
    "ArtifactPersistenceError",
    "BASELINE_CLASSIFIER_NAME",
    "BASELINE_CONTRACT_VERSION",
    "BASELINE_REGRESSOR_NAME",
    "BaselineEvaluation",
    "BaselineEvaluationError",
    "CANDIDATE_CLASSIFIER_NAMES",
    "CANDIDATE_REGRESSOR_NAMES",
    "CandidateRegressionValidationMetrics",
    "CandidateValidationMetrics",
    "CategoricalLevel",
    "CategoricalSummary",
    "ChronologicalSplit",
    "ClassificationBalance",
    "ClassificationBaselineMetrics",
    "CLASSIFICATION_FEATURE_COLUMNS",
    "CleaningResult",
    "ConfigError",
    "CorruptionEntry",
    "CorruptionManifest",
    "DataQualitySummary",
    "DateSummary",
    "EDAError",
    "EDAReport",
    "ENV_PREFIX",
    "FEATURE_COLUMNS",
    "FEATURE_FRAME_COLUMNS",
    "FEATURE_KEY_COLUMNS",
    "FEATURE_REGISTRY",
    "FROZEN_SELECTION_CONTRACT_VERSION",
    "FrozenSelectionError",
    "FrozenSelectionResult",
    "DatasetSpec",
    "DatabaseConfigurationError",
    "DatabaseUnavailableError",
    "GenerationError",
    "FeatureDefinition",
    "FeatureInputError",
    "LoadReport",
    "NumericSummary",
    "PersistenceConflict",
    "PersistenceError",
    "PostgresRepository",
    "PreprocessingError",
    "PreprocessorFit",
    "REGRESSION_FEATURE_COLUMNS",
    "RegressionBaselineMetrics",
    "RiskBand",
    "RiskBands",
    "RISK_BAND_NAMES",
    "RiskOutput",
    "RoadGuardConfig",
    "RepositoryExport",
    "RepositoryInputError",
    "SegmentHistory",
    "SelectedArtifactManifest",
    "SegmentMaster",
    "SplitInventory",
    "TARGET_COLUMNS",
    "TargetCorrelation",
    "TestClassificationMetrics",
    "TestRegressionMetrics",
    "TransformedData",
    "V1Contract",
    "ValidationIssue",
    "ValidationReport",
    "__version__",
    "clean_raw_dataset",
    "build_eda_report",
    "build_feature_frame",
    "create_database_engine",
    "days_until_maintenance",
    "decay_condition",
    "derive_observation_targets",
    "evaluate_advanced_classifier",
    "evaluate_advanced_regressor",
    "evaluate_baselines",
    "generate_accident_timeline",
    "generate_maintenance_events",
    "generate_observations",
    "generate_segments",
    "fit_preprocessor",
    "inject_observation_corruption",
    "initialize_database",
    "load_config",
    "load_cleaning_result",
    "maintenance_within_30_days",
    "month_transition",
    "monthly_hazard",
    "observation_dates",
    "persist_selected_artifacts",
    "risk_score_from_probability",
    "render_data_card",
    "split_chronologically",
    "transform",
    "validate_cleaned_dataset",
    "validate_raw_dataset",
]
