"""Tests for package metadata and the public API surface."""

from __future__ import annotations

import re

import roadguard


def test_package_imports_and_exposes_semver_version() -> None:
    assert re.fullmatch(r"\d+\.\d+\.\d+", roadguard.__version__) is not None


def test_public_api_surface() -> None:
    expected = (
        "ADVANCED_REGRESSOR_CONTRACT_VERSION",
        "ADVANCED_REGRESSOR_RNG_NAMESPACE",
        "ADVANCED_CLASSIFIER_CONTRACT_VERSION",
        "ADVANCED_CLASSIFIER_RNG_NAMESPACE",
        "AdvancedClassificationError",
        "AdvancedClassificationEvaluation",
        "AdvancedRegressionError",
        "AdvancedRegressionEvaluation",
        "ARTIFACT_FILENAMES",
        "ArtifactFile",
        "ArtifactPersistenceError",
        "BASELINE_CLASSIFIER_NAME",
        "BASELINE_CONTRACT_VERSION",
        "BASELINE_REGRESSOR_NAME",
        "BaselineEvaluation",
        "BaselineEvaluationError",
        "CANDIDATE_CLASSIFIER_NAMES",
        "CandidateValidationMetrics",
        "CANDIDATE_REGRESSOR_NAMES",
        "CandidateRegressionValidationMetrics",
        "CategoricalLevel",
        "CategoricalSummary",
        "ChronologicalSplit",
        "ClassificationBalance",
        "ClassificationBaselineMetrics",
        "CleaningResult",
        "ConfigError",
        "CorruptionEntry",
        "CorruptionManifest",
        "DataQualitySummary",
        "DateSummary",
        "EDAError",
        "EDAReport",
        "ENV_PREFIX",
        "FROZEN_SELECTION_CONTRACT_VERSION",
        "FrozenSelectionError",
        "FrozenSelectionResult",
        "DatasetSpec",
        "DatabaseConfigurationError",
        "DatabaseUnavailableError",
        "GenerationError",
        "LoadReport",
        "MAINTENANCE_OPTIMIZATION_CONTRACT_VERSION",
        "MAINTENANCE_OPTIMIZATION_USE_CASE",
        "MAX_EXACT_VND",
        "MaintenanceCostInput",
        "MaintenanceOptimizationError",
        "MaintenanceOptimizationResult",
        "MaintenanceRecommendation",
        "PersistenceConflict",
        "PersistenceError",
        "PostgresRepository",
        "PreprocessingError",
        "PreprocessorFit",
        "REGRESSION_FEATURE_COLUMNS",
        "RegressionBaselineMetrics",
        "RiskBand",
        "RiskBands",
        "RISK_BAND_NAMES",
        "RiskOutput",
        "RoadGuardConfig",
        "RepositoryExport",
        "RepositoryInputError",
        "SegmentHistory",
        "SelectedArtifactManifest",
        "SegmentMaster",
        "SplitInventory",
        "TARGET_COLUMNS",
        "TestRegressionMetrics",
        "TargetCorrelation",
        "TestClassificationMetrics",
        "TransformedData",
        "V1Contract",
        "V1_OPTIMIZATION_CANDIDATE_COUNT",
        "ValidationIssue",
        "ValidationReport",
        "clean_raw_dataset",
        "build_eda_report",
        "create_database_engine",
        "days_until_maintenance",
        "decay_condition",
        "derive_observation_targets",
        "evaluate_advanced_classifier",
        "evaluate_advanced_regressor",
        "evaluate_baselines",
        "generate_accident_timeline",
        "generate_maintenance_events",
        "generate_observations",
        "generate_segments",
        "fit_preprocessor",
        "inject_observation_corruption",
        "initialize_database",
        "load_config",
        "load_cleaning_result",
        "maintenance_within_30_days",
        "month_transition",
        "monthly_hazard",
        "observation_dates",
        "optimize_maintenance",
        "persist_selected_artifacts",
        "risk_score_from_probability",
        "render_data_card",
        "split_chronologically",
        "transform",
        "validate_cleaned_dataset",
        "validate_raw_dataset",
    )
    for name in expected:
        assert hasattr(roadguard, name), f"missing public attribute: {name}"
